#LU CONFIG
#FOR COSTUM PLUGINS, DM ME ON DISCORD
#THIS PLUGIN IS MADE BY THEBJOREDCRAFT
#SUPPORT ON DISCORD: https://discord.gg/tEx5B2pJ
#YOU CAN USE COLORCODES WITH MiniMessage! https://webui.advntr.dev/

#MainPrefix: "LuckUtils | "
#ErrorPrefix: "[ERROR] LuckUtils | "
#: "[WARN] LuckUtils | "
#InfoLuckUtils: "[INFO] LuckUtils | "


#  PLAYERLIST - TABLIST ----------------------------------------------
AnimatedTablist: true

FirstTablistHeader: "<color:#78ffb5>DEIN NETWORK</color>"
FirstTablistPlayerName: "%prefix% <dark_gray>|</dark_gray> %playername% %registered%"
FirstTablistFooter: "<color:#ff0004>LuckUtils v7.0 - by TheBjoRedCraft</color>"

SecondTablistHeader: "<color:#78ffb5>DEIN NETWORK</color>"
SecondTablistPlayerName: "%prefix% <dark_gray>|</dark_gray> %playername% %registered%"
SecondTablistFooter: "<color:#ff0004>Deine Infos!</color>"

SwitchTabList: 600

UpdateTabList: true
#IN TICKS - 20 Ticks = 1 sec
Repeat: 20

# CHATFORMAT --------------------------------------------------------

#PLACEHOLDER:
#%luckperms_prefix% = Gives the Prefix of the Player
#%playername% = Gives the Playername of the Player
#%message% = Returns the Message

ChatFormat: "%luckperms_prefix% <dark_gray>|</dark_gray> %playername% <dark_gray>>></dark_gray> %message%"

# Registered --------------------------------------------------------

RegPermisson: "lu.registered"
RegFormatOn: "<green><bold>✓"
RegFormatOff: ""

